### PR TITLE
Setup Jekyll for site generation

### PR DESCRIPTION
**Pull request by FrederikBolding**
Sets up Jekyll site generation based on the EIP repository. Multiple changes have however been made to accommodate formatting differences between CAIPs and EIPs.

Preview: https://frederikbolding.com/CAIPs/

### CODE REVIEW

**Comment by ukstv** [comment]
Jekyll is a pain to install on Apple Silicon, but this PR is really good.

**Comment by FrederikBolding** [comment]
> Jekyll is a pain to install on Apple Silicon, but this PR is really good.

Yeah, I had to troubleshoot a bit to get it running as well. But once I got it running it was smooth sailing!

**Comment by orenyomtov** [comment]
I'd love to take a look at the preview, but the [preview link](https://frederikbolding.com/CAIPs/) and [CNAME](chainagnostic.org) are redirecting to https://github.com/ChainAgnostic/CASA - is that on purpose?

**Comment by FrederikBolding** [comment]
> I'd love to take a look at the preview, but the [preview link](https://frederikbolding.com/CAIPs/) and [CNAME](chainagnostic.org) are redirecting to https://github.com/ChainAgnostic/CASA - is that on purpose?

Ah, sorry! I broke the preview just now by adding the `CNAME`. 

@ligi requested I add the CNAME as it will be needed when this is merged.

I have fixed the preview link by deploying a [separate branch](https://github.com/FrederikBolding/CAIPs/tree/fb/jekyll-preview) to GitHub pages. The `CNAME` will keep redirecting until the DNS is updated.

**Review by ligi — APPROVED** [review]

**Pull request merged**
