### PR TITLE
Rename namespaces

### PR DESCRIPTION
**Pull request by pedrouid**
Related to #51

### CODE REVIEW

**Comment by ligi** [comment]
I am lightly against this change - IMHO before it was more specific and I also see no good reason for this breaking change. So I would signal to not do it. Not an "over my dead body" tough - just a light preference. So if the majority wants this change we can merge it - maybe we should do a vote in the CASA call.

**Comment by bohendo** [comment]
FWIW, I'm going to start using this new multi-chain address format in my projects whether or not this PR actually gets merged.

The new format is dope:
 - doesn't leak irrelevant details re Ethereum's governance process
 - uses recognizable namespaces that give devs useful context & won't intimidate users.
 - new endianess means you get more useful info w a quick glance at the first dozen chars of an address
 - new endianess also groups namespaces together when you sort them

**Comment by pedrouid** [comment]
My main motivation for making this change as aggressively as this is:
a) these specs are in DRAFT status
b) starting to see examples in the wild as @bohendo mentioned that use these new namespaces 

But 100% agree @ligi these PRs are in preparation of the CASA meeting for next week

Once we get the voting for these PRs then we should merge them

**Comment by pedrouid** [comment]
Replaced by #59

**Pull request closed without merging**
