### PR TITLE
Adds new CAIP as superset of CAIP-10

### PR DESCRIPTION
**Pull request by bumblefudge**

### CODE REVIEW

**Comment by oed** [comment]
Why can't this be an update to caip10?

**Comment by oed** [comment]
If these changes are backwards compatible we should just update caip10 since it's still in draft stage.

**Comment by bumblefudge** [comment]
> If these changes are backwards compatible

I thought Ceramic's implementation failed validation when `.` or `%` was present? I'm not sure what legacy compatibility issues it would create for other implementers (WC, Spruce, etc.), but this "supersession" approach was the concensus when we talked about it 2 or 3 editorial meetings ago... let's discuss Thursday at the next one!

**Comment by oed** [comment]
We use the js-caip library. I'm sure it can be updated to support this
change?

*Joel Thorstensson *
Tech co-founder,
[image: 3Box Labs] <https://3boxlabs.com>

**Pull request closed without merging**
