### PR TITLE
Draft: Add CAIP-2 for Algorand blockchain

### PR DESCRIPTION
**Pull request by aetherplex**
Draft of CAIP-2 for the Algorand blockchain.

### CODE REVIEW

**Comment by tahpot** [comment]
Can this be merged? We want to use it at Verida.

**Comment by oed** [comment]
All blockchain specific specifications are moving to the namespaces repo: https://github.com/ChainAgnostic/namespaces/pulls
Please submit a PR there for this to be added!

**Comment by jasonpaulos** [comment]
I've opened a PR in that repo: https://github.com/ChainAgnostic/namespaces/pull/48

**Comment by obstropolos** [comment]
Closing here because of [namespaces #48](https://github.com/ChainAgnostic/namespaces/pull/48) being open

**Pull request closed without merging**
