### PR TITLE
Support underscores in chain ID reference

### PR DESCRIPTION
**Pull request by delaaxe**
Adding support for underscores in the chain id reference allows using StarkNet chain ids as-is (`SN_MAIN`, `SN_GOERLI`) without having to do error-prone translations in both dapps and wallets.

Such a change shouldn't impact the existing requirements for the reference.

### CODE REVIEW

**Comment by oed** [comment]
Could you also add a PR to add starknet to the namespaces repo?
https://github.com/ChainAgnostic/namespaces/

**Comment by delaaxe** [comment]
> Could you also add a PR to add starknet to the namespaces repo? https://github.com/ChainAgnostic/namespaces/

Will do the PR.

Drafting this one for now as there may be better ways of representing StarkNet chain ids that don't require this change.

**Comment by oed** [comment]
@pedrouid any reason not to add support for `_`?

**Comment by delaaxe** [comment]
@oed @pedrouid here is PR for `namespaces`: https://github.com/ChainAgnostic/namespaces/pull/39

**Review by pedrouid — APPROVED** [review]
LGTM 👍

**Review by bumblefudge — APPROVED** [review]

**Comment by bumblefudge** [comment]
@delaaxe this LGTM but maybe we can get the namespace finalized by thursday the 15th so that we don't have an example in a CAIP that isn't backed up by a namespace entry?

**Pull request merged**
