### PR TITLE
Put CAIP-25 in `Review` for experimental implementations 🎉

### PR DESCRIPTION
**Pull request by bumblefudge**

### CODE REVIEW

**Comment by pedrouid** [comment]
Quick note @bumblefudge... the `sessionProperties` field must be moved outside of the `sessionNamespaces` field in the example for a successful response.. After that we can move CAIP-25 into Review 💪

**Comment by bumblefudge** [comment]
🤦

**Review by pedrouid — APPROVED** [review]
👍

**Comment by pedrouid** [comment]
@hmalik88 @ritave how does it look for you guys? Let’s move it to Review stage?

**Comment by hmalik88** [comment]
@pedrouid LGTM

**Comment by pedrouid** [comment]
@bumblefudge let's merge 💪

**Pull request merged**
