### PR TITLE
Maximum Lengths for CAIPs

### PR DESCRIPTION
**Pull request by pedrouid**
This proposal updates maximum lengths for CAIP-2, CAIP-10 and CAIP-19

Previous maximum lengths favored the utf-8 string length within standard sizes like 64 and 128 characters however these included the separators. 

This would then create the situation where namespaces, references and addresses had uncommon maximum lengths (47 and 63)  to accommodate for the separators.

Additionally they were unnecessarily long and since now we have quite a few namespace standards specified under CAIPs we can observe that chain namespaces are no longer than 8 characters and chain references are no longer than 32 characters.

Finally these new proposed maximum lengths allow for cleaner byte encoding with fixed lengths without the need of separators

### CODE REVIEW

**Comment by webmaster128** [comment]
> Finally these new proposed maximum lengths allow for cleaner byte encoding with fixed lengths without the need of separators

How do you do that. They are still variable length, so you cannot simply use e.g. 8+32 = 40 bytes to encode a (namespace, reference) pair.

**Review by webmaster128 — COMMENTED** [review]
No strong opinion on this change in general. But https://github.com/ChainAgnostic/CAIPs/blob/master/CAIPs/caip-5.md needs to be carefully reviewed after this change. There we hash everything longer than 47.

**Comment by pedrouid** [comment]
Thanks for the feedback @webmaster128 💪 I've updated CAIP-3, CAIP-5 and CAIP-20 to match the new max length restrictions

**Review by webmaster128 — APPROVED** [review]
Looks reasonable to me. But I don't know who is enforcing those rules today and if that breaks people's code.

Would be good to hear from actual users. Carefully approving.

**Comment by pedrouid** [comment]
I would like to have your feedback 👌  @antoineherzog @ligi

**Comment by ligi** [comment]
I have no strong opinion on this one - happy either way.

**Comment by antoineherzog** [comment]
No strong opinion as well. All good for me either way.

**Comment by pedrouid** [comment]
Great 🙌  Looks like we have 4 approvals already which includes authors for all CAIPs. Could we get this merged @ligi ?

**Comment by reneromeroverdugo1982** [comment]
Verdugo

**Pull request merged**
