### PR TITLE
fix: rename CAIP-29.md to caip-29.md

### PR DESCRIPTION
**Pull request by tarrencev**
Aligns naming with other caip specifications and fixes linking from the parent readme

### CODE REVIEW

**Comment by clehner** [comment]
The index in `README.md` should also be updated now, as #71 changed it to reflect the filename.

**Comment by arslan-raza-143** [comment]
Duplicate of #

**Comment by bumblefudge** [comment]
Happy to fix the TOC in a separate PR

**Comment by ligi** [comment]
readme done in 2108e7f31a8451db272f729871f38a030d28f1c4

**Review by Tesbarmix1 — APPROVED** [review]

**Pull request merged**
